//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallOfElectronics.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public Buy()
        {
            this.Products = new HashSet<Product>();
        }
    
        public long TrackingCode { get; set; }
        public int Day { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public long CustomerID { get; set; }
        public long CardNumber { get; set; }
    
        public virtual BankCard BankCard { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
