//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallOfElectronics.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesFeature
    {
        public CategoriesFeature()
        {
            this.CategoriesFeatures1 = new HashSet<CategoriesFeature>();
            this.Products = new HashSet<Product>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual ICollection<CategoriesFeature> CategoriesFeatures1 { get; set; }
        public virtual CategoriesFeature CategoriesFeature1 { get; set; }
        public virtual ICollection<Product> Products { get; set; }
    }
}
