//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallOfElectronics.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyCategory
    {
        public CompanyCategory()
        {
            this.Companies = new HashSet<Company>();
            this.CompanyCategory1 = new HashSet<CompanyCategory>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ParentId { get; set; }
    
        public virtual ICollection<Company> Companies { get; set; }
        public virtual ICollection<CompanyCategory> CompanyCategory1 { get; set; }
        public virtual CompanyCategory CompanyCategory2 { get; set; }
    }
}
