//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallOfElectronics.Models.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MallOfElectronicsEntities : DbContext
    {
        public MallOfElectronicsEntities()
            : base("name=MallOfElectronicsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BankCard> BankCards { get; set; }
        public DbSet<Buy> Buys { get; set; }
        public DbSet<CategoriesEntity> CategoriesEntities { get; set; }
        public DbSet<CategoriesFeature> CategoriesFeatures { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<CompanyCategory> CompanyCategories { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<PhoneSupport> PhoneSupports { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductCategory> ProductCategories { get; set; }
    }
}
