//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallOfElectronics.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneSupport
    {
        public long id { get; set; }
        public long CompanyId { get; set; }
        public long PhoneSupport1 { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
