//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallOfElectronics.Models.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Buys = new HashSet<Buy>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int Price { get; set; }
        public string Color { get; set; }
        public int Count { get; set; }
        public long CompanyId { get; set; }
        public long ProductIDCategories { get; set; }
        public double Weight { get; set; }
        public int ProductType { get; set; }
        public Nullable<double> ScreenSize { get; set; }
        public Nullable<double> MemorySize { get; set; }
        public string Brand { get; set; }
        public Nullable<double> PrecisionCamera { get; set; }
        public Nullable<long> IdOfCategoryFeatures { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    
        public virtual CategoriesFeature CategoriesFeature { get; set; }
        public virtual Company Company { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual ICollection<Buy> Buys { get; set; }
    }
}
